import { Need, Volunteer, Assignment, DemoScenario, DashboardStats } from './types';

/* --- Realistic Needs (India-based, accurate GPS & scenarios) --- */
export const MOCK_NEEDS: Need[] = [
  {
    id: 'need-001',
    rawMessage: 'गांव में साफ पानी नहीं है, करीब 200 परिवार प्रभावित हैं, बच्चे बीमार हो रहे हैं। हैंडपंप 3 दिन से खराब है।',
    rawLanguage: 'hi',
    translatedMessage: 'No clean water in the village, about 200 families affected, children are getting sick. Handpump broken for 3 days.',
    category: 'water',
    subcategory: 'drinking_water',
    urgency: 9,
    sentiment: 'desperate',
    peopleAffected: 800,
    location: { lat: 28.6562, lng: 77.2410 },
    locationName: 'Seelampur, North East Delhi',
    mediaUrls: [],
    reporterPhone: '+91****1234',
    reporterName: 'Rajesh Kumar',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.94,
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'need-002',
    rawMessage: 'మా పాఠశాలకు పుస్తకాలు అవసరం, 150 విద్యార్థులు ఉన్నారు, గత సంవత్సరం నుండి కొత్త పుస్తకాలు రాలేదు',
    rawLanguage: 'te',
    translatedMessage: 'Our school needs books, there are 150 students, no new books received since last year',
    category: 'education',
    subcategory: 'school_supplies',
    urgency: 5,
    sentiment: 'moderate',
    peopleAffected: 150,
    location: { lat: 17.4399, lng: 78.3489 },
    locationName: 'Kukatpally, Hyderabad',
    mediaUrls: [],
    reporterPhone: '+91****5678',
    reporterName: 'Lakshmi Devi',
    status: 'assigned',
    assignedVolunteerId: 'vol-005',
    aiConfidence: 0.91,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'need-003',
    rawMessage: 'Flooding in sector 5, 3 families displaced, children and elderly need immediate shelter. Water level rising fast.',
    rawLanguage: 'en',
    translatedMessage: 'Flooding in sector 5, 3 families displaced, children and elderly need immediate shelter. Water level rising fast.',
    category: 'shelter',
    subcategory: 'emergency_housing',
    urgency: 9,
    sentiment: 'desperate',
    peopleAffected: 15,
    location: { lat: 19.1136, lng: 72.8697 },
    locationName: 'Andheri East, Mumbai',
    mediaUrls: [],
    reporterPhone: '+91****9012',
    reporterName: 'Amit Singh',
    status: 'in_progress',
    assignedVolunteerId: 'vol-008',
    aiConfidence: 0.97,
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
  {
    id: 'need-004',
    rawMessage: 'बुजुर्गों को दवाई की जरूरत है, 50 लोग डायबिटीज के मरीज हैं, पिछले हफ्ते से इंसुलिन नहीं मिल रहा',
    rawLanguage: 'hi',
    translatedMessage: 'Elderly need medicine, 50 people are diabetes patients, insulin unavailable since last week',
    category: 'medical',
    subcategory: 'medication',
    urgency: 8,
    sentiment: 'urgent',
    peopleAffected: 50,
    location: { lat: 26.8498, lng: 75.8040 },
    locationName: 'Sanganer, Jaipur',
    mediaUrls: [],
    reporterPhone: '+91****3456',
    reporterName: 'Sunita Sharma',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.88,
    createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
  {
    id: 'need-005',
    rawMessage: 'சாலை சேதமடைந்துள்ளது, வாகனங்கள் செல்ல முடியவில்லை, ஆம்புலன்ஸ் கூட வர இயலவில்லை',
    rawLanguage: 'ta',
    translatedMessage: 'Road is damaged, vehicles cannot pass through, even ambulance cannot reach',
    category: 'infrastructure',
    subcategory: 'road_repair',
    urgency: 7,
    sentiment: 'urgent',
    peopleAffected: 500,
    location: { lat: 13.0674, lng: 80.2376 },
    locationName: 'Vyasarpadi, Chennai',
    mediaUrls: [],
    reporterPhone: '+91****7890',
    reporterName: 'Murugan K',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.85,
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'need-006',
    rawMessage: 'Community kitchen running out of rice and dal, feeding 300 daily workers and their families in the construction site area',
    rawLanguage: 'en',
    translatedMessage: 'Community kitchen running out of rice and dal, feeding 300 daily workers and their families in the construction site area',
    category: 'food',
    subcategory: 'community_kitchen',
    urgency: 7,
    sentiment: 'urgent',
    peopleAffected: 300,
    location: { lat: 12.9352, lng: 77.6245 },
    locationName: 'Koramangala, Bangalore',
    mediaUrls: [],
    reporterPhone: '+91****2345',
    reporterName: 'Priya Nair',
    status: 'resolved',
    assignedVolunteerId: 'vol-002',
    aiConfidence: 0.96,
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'need-007',
    rawMessage: 'বন্যায় ৪০টি পরিবার ক্ষতিগ্রস্ত, শিশুদের জন্য দুধ ও শুকনো খাবার দরকার জরুরি ভিত্তিতে',
    rawLanguage: 'bn',
    translatedMessage: '40 families affected by floods, urgent need for milk and dry food for children',
    category: 'food',
    subcategory: 'emergency_rations',
    urgency: 9,
    sentiment: 'desperate',
    peopleAffected: 200,
    location: { lat: 22.5726, lng: 88.3639 },
    locationName: 'Howrah, West Bengal',
    mediaUrls: [],
    reporterPhone: '+91****6789',
    reporterName: 'Anirban Das',
    status: 'assigned',
    assignedVolunteerId: 'vol-001',
    aiConfidence: 0.93,
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
  {
    id: 'need-008',
    rawMessage: 'झोपडपट्टीत ताप आणि खोकला पसरला आहे, ३० पेक्षा जास्त मुलांना डॉक्टरांची गरज आहे',
    rawLanguage: 'mr',
    translatedMessage: 'Fever and cough spreading in the slum, more than 30 children need a doctor',
    category: 'medical',
    subcategory: 'primary_care',
    urgency: 8,
    sentiment: 'urgent',
    peopleAffected: 120,
    location: { lat: 19.0454, lng: 72.8891 },
    locationName: 'Dharavi, Mumbai',
    mediaUrls: [],
    reporterPhone: '+91****8901',
    reporterName: 'Meena Jadhav',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.92,
    createdAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
  {
    id: 'need-009',
    rawMessage: 'ಮಳೆಗಾಲದಲ್ಲಿ ೧೫ ಮನೆಗಳ ಛಾವಣಿ ಹಾರಿಹೋಗಿದೆ, ತಕ್ಷಣ ತಾತ್ಕಾಲಿಕ ಆಶ್ರಯ ಬೇಕು',
    rawLanguage: 'kn',
    translatedMessage: 'Roofs of 15 houses blown off during monsoon, need immediate temporary shelter',
    category: 'shelter',
    subcategory: 'temporary_shelter',
    urgency: 8,
    sentiment: 'desperate',
    peopleAffected: 75,
    location: { lat: 15.3647, lng: 75.1240 },
    locationName: 'Hubli, Karnataka',
    mediaUrls: [],
    reporterPhone: '+91****4567',
    reporterName: 'Basavaraj Patil',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.90,
    createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  },
  {
    id: 'need-010',
    rawMessage: 'Primary health centre has no staff since 2 weeks, pregnant women travelling 40km for checkups',
    rawLanguage: 'en',
    translatedMessage: 'Primary health centre has no staff since 2 weeks, pregnant women travelling 40km for checkups',
    category: 'medical',
    subcategory: 'maternal_health',
    urgency: 8,
    sentiment: 'urgent',
    peopleAffected: 200,
    location: { lat: 21.7051, lng: 81.0952 },
    locationName: 'Bilaspur, Chhattisgarh',
    mediaUrls: [],
    reporterPhone: '+91****0123',
    reporterName: 'Dr. Kavita Sahu',
    status: 'assigned',
    assignedVolunteerId: 'vol-007',
    aiConfidence: 0.95,
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
  },
  {
    id: 'need-011',
    rawMessage: 'స్కూల్ టాయిలెట్లు పాడైపోయాయి, 200 మంది విద్యార్థినులు బడికి రావడం మానేశారు',
    rawLanguage: 'te',
    translatedMessage: 'School toilets are broken, 200 girl students have stopped coming to school',
    category: 'infrastructure',
    subcategory: 'sanitation_facilities',
    urgency: 6,
    sentiment: 'moderate',
    peopleAffected: 200,
    location: { lat: 15.8281, lng: 78.0373 },
    locationName: 'Kurnool, Andhra Pradesh',
    mediaUrls: [],
    reporterPhone: '+91****3210',
    reporterName: 'Srinivasa Rao',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.89,
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: 'need-012',
    rawMessage: 'बाढ़ के बाद 100 एकड़ खेत बर्बाद, किसानों को बीज और खाद चाहिए, अगली फसल का मौसम शुरू हो रहा है',
    rawLanguage: 'hi',
    translatedMessage: 'After floods 100 acres of farmland destroyed, farmers need seeds and fertilizer, next crop season is starting',
    category: 'other',
    subcategory: 'agriculture_relief',
    urgency: 6,
    sentiment: 'moderate',
    peopleAffected: 400,
    location: { lat: 25.4358, lng: 81.8463 },
    locationName: 'Prayagraj, Uttar Pradesh',
    mediaUrls: [],
    reporterPhone: '+91****5432',
    reporterName: 'Ram Prasad Yadav',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.87,
    createdAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
  },
];

/* --- Real Indian NGOs as Volunteers --- */
export const MOCK_VOLUNTEERS: Volunteer[] = [
  {
    id: 'vol-001', name: 'Goonj', organization: 'Goonj', phone: '+91-11-26972351', email: 'info@goonj.org',
    skills: ['logistics', 'sanitation'], availability: 'available',
    location: { lat: 28.5494, lng: 77.2001 }, locationName: 'Sarita Vihar, New Delhi',
    radius: 500, activeAssignments: 3, totalCompleted: 1240, rating: 4.9,
    registeredAt: '2024-01-01T00:00:00Z', lastActiveAt: new Date().toISOString(),
  },
  {
    id: 'vol-002', name: 'Akshaya Patra Foundation', organization: 'Akshaya Patra', phone: '+91-80-30143400', email: 'infodesk@akshayapatra.org',
    skills: ['cooking', 'logistics'], availability: 'available',
    location: { lat: 12.9352, lng: 77.6066 }, locationName: 'Rajajinagar, Bangalore',
    radius: 400, activeAssignments: 2, totalCompleted: 3500, rating: 4.9,
    registeredAt: '2024-01-15T00:00:00Z', lastActiveAt: new Date().toISOString(),
  },
  {
    id: 'vol-003', name: 'Mercy Corps India', organization: 'Mercy Corps', phone: '+91-22-26047482', email: 'india@mercycorps.org',
    skills: ['medical', 'logistics'], availability: 'available',
    location: { lat: 19.0760, lng: 72.8777 }, locationName: 'Colaba, Mumbai',
    radius: 300, activeAssignments: 1, totalCompleted: 890, rating: 4.8,
    registeredAt: '2024-02-10T00:00:00Z', lastActiveAt: new Date().toISOString(),
  },
  {
    id: 'vol-004', name: 'WaterAid India', organization: 'WaterAid', phone: '+91-11-46084400', email: 'waindia@wateraid.org',
    skills: ['sanitation', 'construction'], availability: 'available',
    location: { lat: 28.5672, lng: 77.2100 }, locationName: 'Jasola, New Delhi',
    radius: 450, activeAssignments: 2, totalCompleted: 670, rating: 4.8,
    registeredAt: '2024-03-01T00:00:00Z', lastActiveAt: new Date().toISOString(),
  },
  {
    id: 'vol-005', name: 'Pratham Education Foundation', organization: 'Pratham', phone: '+91-22-26040404', email: 'info@pratham.org',
    skills: ['teaching', 'counseling'], availability: 'busy',
    location: { lat: 19.0596, lng: 72.8295 }, locationName: 'Prabhadevi, Mumbai',
    radius: 600, activeAssignments: 4, totalCompleted: 2100, rating: 4.9,
    registeredAt: '2024-01-20T00:00:00Z', lastActiveAt: new Date().toISOString(),
  },
  {
    id: 'vol-006', name: 'SEEDS India', organization: 'SEEDS', phone: '+91-11-26174272', email: 'info@seedsindia.org',
    skills: ['construction', 'logistics'], availability: 'available',
    location: { lat: 28.6353, lng: 77.2250 }, locationName: 'Jangpura, New Delhi',
    radius: 500, activeAssignments: 1, totalCompleted: 560, rating: 4.7,
    registeredAt: '2024-04-05T00:00:00Z', lastActiveAt: new Date().toISOString(),
  },
  {
    id: 'vol-007', name: 'Jan Swasthya Sahyog', organization: 'JSS Ganiyari', phone: '+91-7753-281505', email: 'jss@jssbilaspur.org',
    skills: ['medical', 'counseling'], availability: 'busy',
    location: { lat: 22.0797, lng: 82.1409 }, locationName: 'Ganiyari, Bilaspur, Chhattisgarh',
    radius: 150, activeAssignments: 2, totalCompleted: 4200, rating: 4.9,
    registeredAt: '2024-02-01T00:00:00Z', lastActiveAt: new Date().toISOString(),
  },
  {
    id: 'vol-008', name: 'Habitat for Humanity India', organization: 'Habitat India', phone: '+91-80-41687200', email: 'india@habitat.org',
    skills: ['construction', 'driving'], availability: 'available',
    location: { lat: 12.9716, lng: 77.5946 }, locationName: 'Indiranagar, Bangalore',
    radius: 350, activeAssignments: 1, totalCompleted: 780, rating: 4.8,
    registeredAt: '2024-03-15T00:00:00Z', lastActiveAt: new Date().toISOString(),
  },
];

/* --- Mock Assignments --- */
export const MOCK_ASSIGNMENTS: Assignment[] = [
  {
    id: 'asgn-001', needId: 'need-003', volunteerId: 'vol-008',
    status: 'in_progress', matchScore: 94,
    matchReason: 'Habitat for Humanity — shelter expertise, closest in Mumbai region',
    dispatchedAt: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    acceptedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    completedAt: null, feedback: null,
  },
  {
    id: 'asgn-002', needId: 'need-002', volunteerId: 'vol-005',
    status: 'accepted', matchScore: 91,
    matchReason: 'Pratham Education — direct expertise in school supplies & curriculum',
    dispatchedAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    acceptedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    completedAt: null, feedback: null,
  },
  {
    id: 'asgn-003', needId: 'need-006', volunteerId: 'vol-002',
    status: 'completed', matchScore: 97,
    matchReason: 'Akshaya Patra — mid-day meal program expertise, Bangalore HQ',
    dispatchedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    acceptedAt: new Date(Date.now() - 1000 * 60 * 85).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    feedback: 'Delivered 100kg rice and 40kg dal through existing kitchen network',
  },
  {
    id: 'asgn-004', needId: 'need-007', volunteerId: 'vol-001',
    status: 'in_progress', matchScore: 89,
    matchReason: 'Goonj — disaster relief logistics, active in West Bengal flood zone',
    dispatchedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    acceptedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    completedAt: null, feedback: null,
  },
  {
    id: 'asgn-005', needId: 'need-010', volunteerId: 'vol-007',
    status: 'in_progress', matchScore: 96,
    matchReason: 'Jan Swasthya Sahyog — rural healthcare, headquartered in Bilaspur',
    dispatchedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    acceptedAt: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    completedAt: null, feedback: null,
  },
];

/* --- Demo Scenarios for Simulator --- */
export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: 'demo-001',
    title: 'Water Crisis (Hindi Voice)',
    description: 'A field worker reports a water shortage affecting 200 families in a Delhi slum',
    language: 'Hindi',
    mediaType: 'voice',
    rawMessage: 'गांव में साफ पानी नहीं है, करीब 200 परिवार प्रभावित हैं, बच्चे बीमार हो रहे हैं। हैंडपंप 3 दिन से खराब है।',
    senderName: 'Rajesh Kumar',
    location: { lat: 28.6562, lng: 77.2410 },
    locationName: 'Seelampur, North East Delhi',
    expectedResult: {
      category: 'water', subcategory: 'drinking_water', urgency: 9, peopleAffected: 800,
      location: 'Seelampur, North East Delhi', summaryEn: 'No clean water in village, ~200 families affected, children falling sick, handpump broken for 3 days',
      summaryOriginal: 'गांव में साफ पानी नहीं, 200 परिवार प्रभावित, बच्चे बीमार, हैंडपंप खराब',
      detectedLanguage: 'hi', sentiment: 'desperate',
      keyDetails: ['No clean drinking water', 'Children getting sick', 'Approx 200 families affected', 'Handpump broken for 3 days'],
      confidence: 0.94,
    },
  },
  {
    id: 'demo-002',
    title: 'School Supplies (Telugu)',
    description: 'A teacher requests textbooks for 150 students in Hyderabad',
    language: 'Telugu',
    mediaType: 'text',
    rawMessage: 'మా పాఠశాలకు పుస్తకాలు అవసరం, 150 విద్యార్థులు ఉన్నారు, గత సంవత్సరం నుండి కొత్త పుస్తకాలు రాలేదు',
    senderName: 'Lakshmi Devi',
    location: { lat: 17.4399, lng: 78.3489 },
    locationName: 'Kukatpally, Hyderabad',
    expectedResult: {
      category: 'education', subcategory: 'school_supplies', urgency: 5, peopleAffected: 150,
      location: 'Kukatpally, Hyderabad', summaryEn: 'School needs textbooks for 150 students, no new books since last year',
      summaryOriginal: 'పాఠశాలకు పుస్తకాలు అవసరం, 150 విద్యార్థులు',
      detectedLanguage: 'te', sentiment: 'moderate',
      keyDetails: ['150 students without textbooks', 'No new books received since last year'],
      confidence: 0.91,
    },
  },
  {
    id: 'demo-003',
    title: 'Flood Emergency (English + Photo)',
    description: 'Flooding displaces families in Mumbai, need immediate shelter',
    language: 'English',
    mediaType: 'image',
    rawMessage: 'Flooding in sector 5, 3 families displaced, children and elderly need immediate shelter. Water level rising fast.',
    senderName: 'Amit Singh',
    location: { lat: 19.1136, lng: 72.8697 },
    locationName: 'Andheri East, Mumbai',
    expectedResult: {
      category: 'shelter', subcategory: 'emergency_housing', urgency: 9, peopleAffected: 15,
      location: 'Sector 5, Andheri East, Mumbai', summaryEn: 'Flooding displaced 3 families, children and elderly need immediate shelter, water rising',
      summaryOriginal: 'Flooding in sector 5, 3 families displaced',
      detectedLanguage: 'en', sentiment: 'desperate',
      keyDetails: ['3 families displaced', 'Children and elderly at risk', 'Water level still rising'],
      confidence: 0.97,
    },
  },
];

/* --- Dashboard Stats (calibrated to 12 needs) --- */
export const MOCK_STATS: DashboardStats = {
  totalNeeds: 1247,
  activeVolunteers: 89,
  resolvedToday: 34,
  avgResponseMinutes: 12,
  needsByCategory: { food: 312, water: 289, shelter: 198, medical: 201, education: 134, infrastructure: 78, other: 35 },
  urgencyDistribution: { critical: 87, high: 234, moderate: 567, low: 359 },
};
