import { Need, Volunteer, Assignment, DemoScenario, DashboardStats } from './types';

/* --- Mock Needs (India-based) --- */
export const MOCK_NEEDS: Need[] = [
  {
    id: 'need-001',
    rawMessage: 'गांव में साफ पानी नहीं है, करीब 200 परिवार प्रभावित हैं, बच्चे बीमार हो रहे हैं',
    rawLanguage: 'hi',
    translatedMessage: 'No clean water in the village, about 200 families affected, children are getting sick',
    category: 'water',
    subcategory: 'drinking_water',
    urgency: 9,
    sentiment: 'desperate',
    peopleAffected: 800,
    location: { lat: 28.6139, lng: 77.209 },
    locationName: 'Chandni Chowk, Delhi',
    mediaUrls: [],
    reporterPhone: '+91****1234',
    reporterName: 'Rajesh Kumar',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.94,
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'need-002',
    rawMessage: 'మా పాఠశాలకు పుస్తకాలు అవసరం, 150 విద్యార్థులు ఉన్నారు',
    rawLanguage: 'te',
    translatedMessage: 'Our school needs books, there are 150 students',
    category: 'education',
    subcategory: 'school_supplies',
    urgency: 5,
    sentiment: 'moderate',
    peopleAffected: 150,
    location: { lat: 17.385, lng: 78.4867 },
    locationName: 'Hyderabad, Telangana',
    mediaUrls: [],
    reporterPhone: '+91****5678',
    reporterName: 'Lakshmi Devi',
    status: 'assigned',
    assignedVolunteerId: 'vol-002',
    aiConfidence: 0.91,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'need-003',
    rawMessage: 'Flooding in sector 5, 3 families displaced, need immediate shelter',
    rawLanguage: 'en',
    translatedMessage: 'Flooding in sector 5, 3 families displaced, need immediate shelter',
    category: 'shelter',
    subcategory: 'emergency_housing',
    urgency: 8,
    sentiment: 'urgent',
    peopleAffected: 15,
    location: { lat: 19.076, lng: 72.8777 },
    locationName: 'Andheri, Mumbai',
    mediaUrls: [],
    reporterPhone: '+91****9012',
    reporterName: 'Amit Singh',
    status: 'in_progress',
    assignedVolunteerId: 'vol-001',
    aiConfidence: 0.97,
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
  {
    id: 'need-004',
    rawMessage: 'बुजुर्गों को दवाई की जरूरत है, 50 लोग डायबिटीज के मरीज हैं',
    rawLanguage: 'hi',
    translatedMessage: 'Elderly need medicine, 50 people are diabetes patients',
    category: 'medical',
    subcategory: 'medication',
    urgency: 7,
    sentiment: 'urgent',
    peopleAffected: 50,
    location: { lat: 26.9124, lng: 75.7873 },
    locationName: 'Jaipur, Rajasthan',
    mediaUrls: [],
    reporterPhone: '+91****3456',
    reporterName: 'Sunita Sharma',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.88,
    createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
  {
    id: 'need-005',
    rawMessage: 'சாலை சேதமடைந்துள்ளது, வாகனங்கள் செல்ல முடியவில்லை',
    rawLanguage: 'ta',
    translatedMessage: 'Road is damaged, vehicles cannot pass through',
    category: 'infrastructure',
    subcategory: 'road_repair',
    urgency: 6,
    sentiment: 'moderate',
    peopleAffected: 500,
    location: { lat: 13.0827, lng: 80.2707 },
    locationName: 'Chennai, Tamil Nadu',
    mediaUrls: [],
    reporterPhone: '+91****7890',
    reporterName: 'Murugan K',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.85,
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'need-006',
    rawMessage: 'Community kitchen running out of rice and dal, feeding 300 daily',
    rawLanguage: 'en',
    translatedMessage: 'Community kitchen running out of rice and dal, feeding 300 daily',
    category: 'food',
    subcategory: 'community_kitchen',
    urgency: 7,
    sentiment: 'urgent',
    peopleAffected: 300,
    location: { lat: 12.9716, lng: 77.5946 },
    locationName: 'Bangalore, Karnataka',
    mediaUrls: [],
    reporterPhone: '+91****2345',
    reporterName: 'Priya Nair',
    status: 'resolved',
    assignedVolunteerId: 'vol-003',
    aiConfidence: 0.96,
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
];

/* --- Mock Volunteers --- */
export const MOCK_VOLUNTEERS: Volunteer[] = [
  {
    id: 'vol-001', name: 'Priya Mehta', phone: '+91****1111', email: 'priya@example.com',
    skills: ['sanitation', 'logistics'], availability: 'available',
    location: { lat: 19.076, lng: 72.8777 }, locationName: 'Mumbai, Maharashtra',
    radius: 15, activeAssignments: 1, totalCompleted: 23, rating: 4.8,
    registeredAt: '2025-01-15T00:00:00Z', lastActiveAt: new Date().toISOString(),
  },
  {
    id: 'vol-002', name: 'Arjun Reddy', phone: '+91****2222', email: 'arjun@example.com',
    skills: ['teaching', 'counseling'], availability: 'busy',
    location: { lat: 17.385, lng: 78.4867 }, locationName: 'Hyderabad, Telangana',
    radius: 20, activeAssignments: 2, totalCompleted: 15, rating: 4.5,
    registeredAt: '2025-03-10T00:00:00Z', lastActiveAt: new Date().toISOString(),
  },
  {
    id: 'vol-003', name: 'Kavitha S', phone: '+91****3333', email: 'kavitha@example.com',
    skills: ['cooking', 'logistics'], availability: 'available',
    location: { lat: 12.9716, lng: 77.5946 }, locationName: 'Bangalore, Karnataka',
    radius: 10, activeAssignments: 0, totalCompleted: 31, rating: 4.9,
    registeredAt: '2024-11-20T00:00:00Z', lastActiveAt: new Date().toISOString(),
  },
  {
    id: 'vol-004', name: 'Dr. Ramesh Gupta', phone: '+91****4444', email: 'ramesh@example.com',
    skills: ['medical'], availability: 'available',
    location: { lat: 26.9124, lng: 75.7873 }, locationName: 'Jaipur, Rajasthan',
    radius: 25, activeAssignments: 0, totalCompleted: 42, rating: 4.9,
    registeredAt: '2024-08-05T00:00:00Z', lastActiveAt: new Date().toISOString(),
  },
  {
    id: 'vol-005', name: 'Deepak Yadav', phone: '+91****5555', email: 'deepak@example.com',
    skills: ['construction', 'driving'], availability: 'offline',
    location: { lat: 28.6139, lng: 77.209 }, locationName: 'Delhi',
    radius: 30, activeAssignments: 0, totalCompleted: 18, rating: 4.3,
    registeredAt: '2025-02-14T00:00:00Z', lastActiveAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

/* --- Mock Assignments --- */
export const MOCK_ASSIGNMENTS: Assignment[] = [
  {
    id: 'asgn-001', needId: 'need-003', volunteerId: 'vol-001',
    status: 'in_progress', matchScore: 92,
    matchReason: 'Closest volunteer with logistics skills in Mumbai area',
    dispatchedAt: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    acceptedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    completedAt: null, feedback: null,
  },
  {
    id: 'asgn-002', needId: 'need-002', volunteerId: 'vol-002',
    status: 'accepted', matchScore: 88,
    matchReason: 'Teaching skills match, located in Hyderabad',
    dispatchedAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    acceptedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    completedAt: null, feedback: null,
  },
  {
    id: 'asgn-003', needId: 'need-006', volunteerId: 'vol-003',
    status: 'completed', matchScore: 95,
    matchReason: 'Cooking skills, closest volunteer in Bangalore',
    dispatchedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    acceptedAt: new Date(Date.now() - 1000 * 60 * 85).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    feedback: 'Delivered 50kg rice and 20kg dal successfully',
  },
];

/* --- Demo Scenarios for Simulator --- */
export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: 'demo-001',
    title: 'Water Crisis (Hindi Voice)',
    description: 'A field worker reports a water shortage affecting 200 families',
    language: 'Hindi',
    mediaType: 'voice',
    rawMessage: 'गांव में साफ पानी नहीं है, करीब 200 परिवार प्रभावित हैं, बच्चे बीमार हो रहे हैं',
    senderName: 'Rajesh Kumar',
    location: { lat: 28.6139, lng: 77.209 },
    locationName: 'Chandni Chowk, Delhi',
    expectedResult: {
      category: 'water', subcategory: 'drinking_water', urgency: 9, peopleAffected: 800,
      location: 'Chandni Chowk, Delhi', summaryEn: 'No clean water in village, ~200 families affected, children falling sick',
      summaryOriginal: 'गांव में साफ पानी नहीं, 200 परिवार प्रभावित, बच्चे बीमार',
      detectedLanguage: 'hi', sentiment: 'desperate',
      keyDetails: ['No clean drinking water', 'Children getting sick', 'Approx 200 families affected'],
      confidence: 0.94,
    },
  },
  {
    id: 'demo-002',
    title: 'School Supplies (Telugu)',
    description: 'A teacher requests textbooks for 150 students',
    language: 'Telugu',
    mediaType: 'text',
    rawMessage: 'మా పాఠశాలకు పుస్తకాలు అవసరం, 150 విద్యార్థులు ఉన్నారు, గత సంవత్సరం నుండి కొత్త పుస్తకాలు రాలేదు',
    senderName: 'Lakshmi Devi',
    location: { lat: 17.385, lng: 78.4867 },
    locationName: 'Hyderabad, Telangana',
    expectedResult: {
      category: 'education', subcategory: 'school_supplies', urgency: 5, peopleAffected: 150,
      location: 'Hyderabad, Telangana', summaryEn: 'School needs textbooks for 150 students, no new books since last year',
      summaryOriginal: 'పాఠశాలకు పుస్తకాలు అవసరం, 150 విద్యార్థులు',
      detectedLanguage: 'te', sentiment: 'moderate',
      keyDetails: ['150 students without textbooks', 'No new books received since last year'],
      confidence: 0.91,
    },
  },
  {
    id: 'demo-003',
    title: 'Flood Emergency (English + Photo)',
    description: 'Flooding displaces families, need immediate shelter',
    language: 'English',
    mediaType: 'image',
    rawMessage: 'Flooding in sector 5, 3 families displaced, children and elderly need immediate shelter. Water level rising.',
    senderName: 'Amit Singh',
    location: { lat: 19.076, lng: 72.8777 },
    locationName: 'Andheri, Mumbai',
    expectedResult: {
      category: 'shelter', subcategory: 'emergency_housing', urgency: 9, peopleAffected: 15,
      location: 'Sector 5, Andheri, Mumbai', summaryEn: 'Flooding displaced 3 families, children and elderly need immediate shelter',
      summaryOriginal: 'Flooding in sector 5, 3 families displaced',
      detectedLanguage: 'en', sentiment: 'desperate',
      keyDetails: ['3 families displaced', 'Children and elderly at risk', 'Water level still rising'],
      confidence: 0.97,
    },
  },
];

/* --- Mock Dashboard Stats --- */
export const MOCK_STATS: DashboardStats = {
  totalNeeds: 1247,
  activeVolunteers: 89,
  resolvedToday: 34,
  avgResponseMinutes: 12,
  needsByCategory: { food: 312, water: 289, shelter: 198, medical: 201, education: 134, infrastructure: 78, other: 35 },
  urgencyDistribution: { critical: 87, high: 234, moderate: 567, low: 359 },
};
