/* ============================================
   NeedPulse — Seed API
   GET /api/seed
   Populates Firestore with 25 realistic emergency
   reports across India for demo/video purposes.
   ============================================ */

import { NextResponse } from 'next/server';
import { addNeed } from '@/lib/firebase';
import type { NeedCategory, Sentiment, NeedStatus } from '@/lib/types';

interface SeedReport {
  rawMessage: string;
  rawLanguage: string;
  translatedMessage: string;
  category: NeedCategory;
  subcategory: string;
  urgency: number;
  sentiment: Sentiment;
  peopleAffected: number;
  location: { lat: number; lng: number };
  locationName: string;
  mediaUrls: string[];
  reporterPhone: string;
  reporterName: string;
  status: NeedStatus;
  assignedVolunteerId: string | null;
  aiConfidence: number;
}

const SEED_REPORTS: SeedReport[] = [
  // ── MEDICAL ──
  {
    rawMessage: 'बाढ़ के बाद 12 लोग बीमार हो गए हैं, उल्टी और दस्त हो रहे हैं। डॉक्टर की तुरंत जरूरत है।',
    rawLanguage: 'hi',
    translatedMessage: '12 people fell sick after floods — vomiting and diarrhea. Doctor needed urgently.',
    category: 'medical',
    subcategory: 'waterborne_disease',
    urgency: 9,
    sentiment: 'desperate',
    peopleAffected: 12,
    location: { lat: 25.4358, lng: 81.8463 },
    locationName: 'Prayagraj, Uttar Pradesh',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919876543210',
    reporterName: 'Ramesh Kumar',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.92,
  },
  {
    rawMessage: 'Pregnant woman needs emergency evacuation. Water level rising fast in our colony.',
    rawLanguage: 'en',
    translatedMessage: 'Pregnant woman needs emergency evacuation. Water level rising fast in our colony.',
    category: 'medical',
    subcategory: 'emergency_evacuation',
    urgency: 10,
    sentiment: 'desperate',
    peopleAffected: 3,
    location: { lat: 19.0760, lng: 72.8777 },
    locationName: 'Dharavi, Mumbai',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919812345678',
    reporterName: 'Sunita Sharma',
    status: 'assigned',
    assignedVolunteerId: 'vol_001',
    aiConfidence: 0.95,
  },
  {
    rawMessage: 'మా గ్రామంలో 8 మంది పిల్లలకు డెంగ్యూ జ్వరం వచ్చింది. వైద్య సహాయం కావాలి.',
    rawLanguage: 'te',
    translatedMessage: '8 children in our village have dengue fever. Medical help needed.',
    category: 'medical',
    subcategory: 'dengue_fever',
    urgency: 8,
    sentiment: 'urgent',
    peopleAffected: 8,
    location: { lat: 17.3850, lng: 78.4867 },
    locationName: 'Hyderabad, Telangana',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919900112233',
    reporterName: 'Lakshmi Devi',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.88,
  },
  // ── WATER ──
  {
    rawMessage: 'पिछले 3 दिनों से पानी नहीं आ रहा। 200 परिवार प्रभावित हैं। बच्चे प्यासे हैं।',
    rawLanguage: 'hi',
    translatedMessage: 'No water supply for 3 days. 200 families affected. Children are thirsty.',
    category: 'water',
    subcategory: 'water_supply',
    urgency: 9,
    sentiment: 'desperate',
    peopleAffected: 800,
    location: { lat: 28.7041, lng: 77.1025 },
    locationName: 'Rohini, New Delhi',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919988776655',
    reporterName: 'Manoj Tiwari',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.91,
  },
  {
    rawMessage: 'Borewell water has turned yellow and smells bad. 50 houses using this water.',
    rawLanguage: 'en',
    translatedMessage: 'Borewell water contaminated — yellow color and foul smell. 50 houses affected.',
    category: 'water',
    subcategory: 'contaminated_water',
    urgency: 7,
    sentiment: 'urgent',
    peopleAffected: 250,
    location: { lat: 12.9716, lng: 77.5946 },
    locationName: 'Whitefield, Bengaluru',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919845671234',
    reporterName: 'Priya Nair',
    status: 'assigned',
    assignedVolunteerId: 'vol_002',
    aiConfidence: 0.85,
  },
  {
    rawMessage: 'வெள்ளத்தில் குடிநீர் ஆலை மூழ்கிவிட்டது. 500 பேருக்கு தண்ணீர் இல்லை.',
    rawLanguage: 'ta',
    translatedMessage: 'Drinking water plant submerged in flood. 500 people without water.',
    category: 'water',
    subcategory: 'flood_damage',
    urgency: 9,
    sentiment: 'desperate',
    peopleAffected: 500,
    location: { lat: 13.0827, lng: 80.2707 },
    locationName: 'Chennai, Tamil Nadu',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919876001122',
    reporterName: 'Murugan S',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.90,
  },
  // ── FOOD ──
  {
    rawMessage: 'राशन खत्म हो गया है। 30 परिवारों को खाना चाहिए। बच्चों को दूध नहीं मिल रहा।',
    rawLanguage: 'hi',
    translatedMessage: 'Rations exhausted. 30 families need food. Babies have no milk.',
    category: 'food',
    subcategory: 'food_supply',
    urgency: 8,
    sentiment: 'urgent',
    peopleAffected: 120,
    location: { lat: 26.9124, lng: 75.7873 },
    locationName: 'Jaipur, Rajasthan',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919811223344',
    reporterName: 'Geeta Bai',
    status: 'in_progress',
    assignedVolunteerId: 'vol_003',
    aiConfidence: 0.87,
  },
  {
    rawMessage: 'Community kitchen destroyed by cyclone. 150 daily meals were served here.',
    rawLanguage: 'en',
    translatedMessage: 'Cyclone destroyed community kitchen that served 150 daily meals.',
    category: 'food',
    subcategory: 'kitchen_destroyed',
    urgency: 7,
    sentiment: 'urgent',
    peopleAffected: 150,
    location: { lat: 20.2961, lng: 85.8245 },
    locationName: 'Bhubaneswar, Odisha',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919876009988',
    reporterName: 'Bijay Mohanty',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.82,
  },
  {
    rawMessage: 'ভাতের জন্য মানুষ কাঁদছে। গত ২ দিন ধরে খাবার নেই। ৪০ পরিবার।',
    rawLanguage: 'bn',
    translatedMessage: 'People crying for rice. No food for 2 days. 40 families.',
    category: 'food',
    subcategory: 'starvation',
    urgency: 9,
    sentiment: 'desperate',
    peopleAffected: 160,
    location: { lat: 22.5726, lng: 88.3639 },
    locationName: 'Kolkata, West Bengal',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919833445566',
    reporterName: 'Rina Das',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.89,
  },
  // ── SHELTER ──
  {
    rawMessage: '25 घर पूरी तरह ध्वस्त हो गए हैं। लोग खुले आसमान के नीचे हैं।',
    rawLanguage: 'hi',
    translatedMessage: '25 houses completely collapsed. People sleeping under open sky.',
    category: 'shelter',
    subcategory: 'house_collapse',
    urgency: 9,
    sentiment: 'desperate',
    peopleAffected: 100,
    location: { lat: 23.2599, lng: 77.4126 },
    locationName: 'Bhopal, Madhya Pradesh',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919876112233',
    reporterName: 'Shyam Patel',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.93,
  },
  {
    rawMessage: 'Flood water entered 40 homes in our slum. Children and elderly have nowhere to go.',
    rawLanguage: 'en',
    translatedMessage: 'Flood water entered 40 homes in slum. Children and elderly stranded.',
    category: 'shelter',
    subcategory: 'flood_displacement',
    urgency: 8,
    sentiment: 'desperate',
    peopleAffected: 200,
    location: { lat: 18.5204, lng: 73.8567 },
    locationName: 'Hadapsar, Pune',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919845123456',
    reporterName: 'Anita Jadhav',
    status: 'assigned',
    assignedVolunteerId: 'vol_004',
    aiConfidence: 0.88,
  },
  {
    rawMessage: 'ಮನೆಗಳು ಕುಸಿದಿವೆ, 15 ಕುಟುಂಬಗಳು ಶಾಲೆಯಲ್ಲಿ ಆಶ್ರಯ ಪಡೆದಿವೆ.',
    rawLanguage: 'kn',
    translatedMessage: 'Houses collapsed, 15 families sheltering in school building.',
    category: 'shelter',
    subcategory: 'temporary_shelter',
    urgency: 7,
    sentiment: 'urgent',
    peopleAffected: 60,
    location: { lat: 15.3647, lng: 75.1240 },
    locationName: 'Hubli, Karnataka',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919876554433',
    reporterName: 'Basavaraj G',
    status: 'in_progress',
    assignedVolunteerId: 'vol_005',
    aiConfidence: 0.84,
  },
  // ── INFRASTRUCTURE ──
  {
    rawMessage: 'Main bridge collapsed after heavy rains. 3 villages completely cut off from town.',
    rawLanguage: 'en',
    translatedMessage: 'Main bridge collapsed. 3 villages cut off from town after heavy rains.',
    category: 'infrastructure',
    subcategory: 'bridge_collapse',
    urgency: 8,
    sentiment: 'urgent',
    peopleAffected: 2000,
    location: { lat: 21.1702, lng: 72.8311 },
    locationName: 'Surat, Gujarat',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919812009988',
    reporterName: 'Kiran Desai',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.90,
  },
  {
    rawMessage: 'बिजली का खंभा गिर गया है, तार नीचे लटक रहे हैं। बच्चे खेल रहे हैं पास में।',
    rawLanguage: 'hi',
    translatedMessage: 'Electric pole fallen, wires hanging dangerously. Children playing nearby.',
    category: 'infrastructure',
    subcategory: 'electric_hazard',
    urgency: 10,
    sentiment: 'desperate',
    peopleAffected: 50,
    location: { lat: 26.8467, lng: 80.9462 },
    locationName: 'Lucknow, Uttar Pradesh',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919900334455',
    reporterName: 'Ashok Verma',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.94,
  },
  {
    rawMessage: 'Road completely washed away near village. Ambulance cannot reach hospital.',
    rawLanguage: 'en',
    translatedMessage: 'Road washed away. Ambulance unable to reach hospital near village.',
    category: 'infrastructure',
    subcategory: 'road_damage',
    urgency: 9,
    sentiment: 'desperate',
    peopleAffected: 500,
    location: { lat: 15.4909, lng: 73.8278 },
    locationName: 'North Goa, Goa',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919876778899',
    reporterName: 'Nilesh Naik',
    status: 'assigned',
    assignedVolunteerId: 'vol_006',
    aiConfidence: 0.86,
  },
  // ── EDUCATION ──
  {
    rawMessage: 'School building flooded. 200 students have no place to study. Books destroyed.',
    rawLanguage: 'en',
    translatedMessage: 'School flooded — 200 students displaced. All textbooks destroyed.',
    category: 'education',
    subcategory: 'school_damage',
    urgency: 5,
    sentiment: 'moderate',
    peopleAffected: 200,
    location: { lat: 11.0168, lng: 76.9558 },
    locationName: 'Coimbatore, Tamil Nadu',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919845998877',
    reporterName: 'Kavitha R',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.80,
  },
  {
    rawMessage: 'పాఠశాల కూలిపోయింది. 150 మంది విద్యార్థులు ఇంట్లో ఉన్నారు.',
    rawLanguage: 'te',
    translatedMessage: 'School building collapsed. 150 students staying home with no education.',
    category: 'education',
    subcategory: 'school_collapse',
    urgency: 4,
    sentiment: 'moderate',
    peopleAffected: 150,
    location: { lat: 16.5062, lng: 80.6480 },
    locationName: 'Vijayawada, Andhra Pradesh',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919876443322',
    reporterName: 'Srinivas K',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.78,
  },
  // ── MORE CRITICAL REPORTS ──
  {
    rawMessage: 'Landslide blocked the only road. 100 families trapped in mountain village.',
    rawLanguage: 'en',
    translatedMessage: 'Landslide blocked only road to mountain village. 100 families trapped.',
    category: 'infrastructure',
    subcategory: 'landslide',
    urgency: 10,
    sentiment: 'desperate',
    peopleAffected: 400,
    location: { lat: 30.7333, lng: 79.0667 },
    locationName: 'Chamoli, Uttarakhand',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919800112244',
    reporterName: 'Hemant Bisht',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.93,
  },
  {
    rawMessage: 'Earthquake damaged 60 houses. People sleeping outside in cold weather.',
    rawLanguage: 'en',
    translatedMessage: 'Earthquake damaged 60 houses. Residents sleeping outside in freezing cold.',
    category: 'shelter',
    subcategory: 'earthquake_damage',
    urgency: 9,
    sentiment: 'desperate',
    peopleAffected: 300,
    location: { lat: 34.0837, lng: 74.7973 },
    locationName: 'Srinagar, Jammu & Kashmir',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919600778899',
    reporterName: 'Faisal Ahmed',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.91,
  },
  {
    rawMessage: 'चक्रवात से 500 एकड़ फसल नष्ट। किसान भूखे हैं। राशन की जरूरत।',
    rawLanguage: 'hi',
    translatedMessage: 'Cyclone destroyed 500 acres of crops. Farmers starving. Rations needed.',
    category: 'food',
    subcategory: 'crop_destruction',
    urgency: 8,
    sentiment: 'desperate',
    peopleAffected: 350,
    location: { lat: 19.7515, lng: 75.7139 },
    locationName: 'Aurangabad, Maharashtra',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919812556677',
    reporterName: 'Balasaheb Patil',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.87,
  },
  {
    rawMessage: 'Snake bite emergency in flood camp. No anti-venom available. Please send medical team.',
    rawLanguage: 'en',
    translatedMessage: 'Snake bite in flood relief camp. No anti-venom. Medical team needed urgently.',
    category: 'medical',
    subcategory: 'snake_bite',
    urgency: 10,
    sentiment: 'desperate',
    peopleAffected: 1,
    location: { lat: 24.5854, lng: 73.7125 },
    locationName: 'Udaipur, Rajasthan',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919876887766',
    reporterName: 'Dr. Anil Meena',
    status: 'assigned',
    assignedVolunteerId: 'vol_007',
    aiConfidence: 0.96,
  },
  {
    rawMessage: 'ગામમાં પીવાનું પાણી નથી. બાળકો બીમાર પડી રહ્યા છે.',
    rawLanguage: 'gu',
    translatedMessage: 'No drinking water in village. Children falling sick.',
    category: 'water',
    subcategory: 'no_water',
    urgency: 8,
    sentiment: 'urgent',
    peopleAffected: 300,
    location: { lat: 23.0225, lng: 72.5714 },
    locationName: 'Ahmedabad, Gujarat',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919876665544',
    reporterName: 'Jayesh Patel',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.83,
  },
  {
    rawMessage: 'Old age home flooded. 20 elderly residents need immediate evacuation.',
    rawLanguage: 'en',
    translatedMessage: 'Old age home flooded. 20 elderly residents need immediate evacuation.',
    category: 'medical',
    subcategory: 'elderly_evacuation',
    urgency: 10,
    sentiment: 'desperate',
    peopleAffected: 20,
    location: { lat: 9.9312, lng: 76.2673 },
    locationName: 'Kochi, Kerala',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919845112233',
    reporterName: 'Sr. Mary Thomas',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.94,
  },
  {
    rawMessage: 'ମୋ ଗ୍ରାମରେ ବାତ୍ୟା ପରେ ସବୁ ଘର ଭାଙ୍ଗିଗଲା। ସାହାଯ୍ୟ ଦରକାର।',
    rawLanguage: 'or',
    translatedMessage: 'All houses destroyed in our village after cyclone. Help needed.',
    category: 'shelter',
    subcategory: 'cyclone_damage',
    urgency: 9,
    sentiment: 'desperate',
    peopleAffected: 250,
    location: { lat: 19.8135, lng: 85.8312 },
    locationName: 'Puri, Odisha',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919876998877',
    reporterName: 'Sanjay Sahoo',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.88,
  },
  {
    rawMessage: 'Chemical factory leak near slum. 80 people experiencing breathing difficulty.',
    rawLanguage: 'en',
    translatedMessage: 'Chemical factory leak near slum. 80 people with breathing difficulty.',
    category: 'medical',
    subcategory: 'chemical_exposure',
    urgency: 10,
    sentiment: 'desperate',
    peopleAffected: 80,
    location: { lat: 21.1458, lng: 79.0882 },
    locationName: 'Nagpur, Maharashtra',
    mediaUrls: [],
    reporterPhone: 'whatsapp:+919800445566',
    reporterName: 'Aakash Meshram',
    status: 'new',
    assignedVolunteerId: null,
    aiConfidence: 0.95,
  },
];

export async function GET() {
  try {
    let successCount = 0;
    const errors: string[] = [];

    for (const report of SEED_REPORTS) {
      try {
        const id = await addNeed(report);
        if (id) {
          successCount++;
        } else {
          errors.push(`Failed to save: ${report.locationName}`);
        }
      } catch (err) {
        errors.push(`Error saving ${report.locationName}: ${err}`);
      }
    }

    return NextResponse.json({
      success: true,
      message: `✅ Seeded ${successCount} of ${SEED_REPORTS.length} reports to Firestore`,
      errors: errors.length > 0 ? errors : undefined,
    });
  } catch (error) {
    return NextResponse.json(
      { success: false, error: String(error) },
      { status: 500 }
    );
  }
}
